### ISSUE TITLE
Elements disappear when changing line height

### ISSUE THREAD

**Issue by timbrownls20** [arco-design/easy-email#99]
**Description**
Changing line height for a section makes some elements disappear. This also happens when grouping a selection of columns

**To reproduce line height change:**
Place cursor in text and use the Line height field in the Text attributes area.  Increase the line height to 4.  The element disappears
![disappearing elements](https://user-images.githubusercontent.com/20048601/157382791-b5613f3b-68f6-439d-88fd-2fe541a0a9f8.png)
.

**Comment by m-Ryan** [comment]
The dom node will be regenerated after the attribute is modified, images will be requested again.

This problem is due to the fact that these pictures are not cached. When I replaced these few pictures, it didn't happen again.

![image](https://user-images.githubusercontent.com/20615214/157451079-78bc9d5c-2831-41bb-841c-191b26453b51.png)
